### ISSUE TITLE
Missing modules (to be built?)

### ISSUE THREAD

**Issue by edbarbier** [yeatse/opencv-spm#1]
Hi, 

I'm just scratching the surface with OpenCV so my apologies if this is a trivial question.  I find your package and I was wondering why after installing it, the Xcode project isn't able to access some modules? (i.e. core dnn and many others)

Is there something specific to do to access more modules from the Xcode project? 

Thanks in advance :) 

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/11492000/211154561-704dca0b-cc9f-404c-81c2-cee14bd4f34b.png">

**Comment by Yeatse** [comment]
Thanks for reporting. It seems there is a bug in OpenCV causing this library cannot initialize on startup. I just submitted a patch to fix this (https://github.com/opencv/opencv/pull/23111). Before this PR is merged, you can stick to version 4.6.0 to use it normally. Kindly let me know if you have any further question.

**Comment by edbarbier** [comment]
Thanks a lot for jumping on this. I'll keep an eye on the PR and try with v4.6 for now. I really appreciate the help. Happy 2023.

**Comment by yeatse** [comment]
Fixed in v4.8.0+7
