### ISSUE TITLE
Unable To Clone Package With Xcode 15.3

### ISSUE THREAD

**Issue by BlackMirrorz** [yeatse/opencv-spm#21]
Until today the Package was building correctly.
Now however I am getting the following error:
<img width="1386" alt="Screenshot 2024-04-18 at 13 11 24" src="https://github.com/yeatse/opencv-spm/assets/35516944/7c00f740-d134-4944-952c-4446b95426a4">
I have Reset Package Cached, Clean Derived Data etc. 

Any Ideas?

**Comment by yeatse** [comment]
I suspect it's more likely to be an Xcode bug, as `380ffe99a92b3984585515d6b5692e100e4b6221` indeed exists: https://github.com/yeatse/opencv-spm/commit/380ffe99a92b3984585515d6b5692e100e4b6221."

**Comment by BlackMirrorz** [comment]
Ok thank you for all your hard work 🫡
