### ISSUE TITLE
Bad Bundle Executable

### ISSUE THREAD

**Issue by borut-t** [yeatse/opencv-spm#26]
I have added the package to the macos project. Everything runs perfectly until I try to send the app to the App Store Connect. I get the following error:

`Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle OpenCV [com.myApp.pkg/Payload/My.app/Contents/Frameworks/opencv2.framework] property list file. (ID: 1310d0e2-120d-400b-9bc5-7ae25a694465)`

What could be the issue here?

**Comment by yeatse** [comment]
Looks like the same issue as https://github.com/yeatse/opencv-spm/issues/19

We should apply the same fix for macOS as well.

**Comment by borut-t** [comment]
Thanks. Looking forward for the next release 🙏

**Comment by borut-t** [comment]
@yeatse is there a planned fix/release for this issue?

**Comment by yeatse** [comment]
I will work on this over the weekend. For now as a workaround, you can simply remove the opencv2.framework folder from your xcarchive file.

**Comment by yeatse** [comment]
Should be fixed in the latest main branch

**Comment by borut-t** [comment]
It works. Thanks man 🙌
