### ISSUE TITLE
[question]laplacian function available?

### ISSUE THREAD

**Issue by junmcenroe** [yeatse/opencv-spm#4]
Dear yeatse

I successfully install the opencv-spm in my iOS project.
I want to measure blurr of image, so like following 
laplacian = cv2.Laplacian(gray, cv2.CV_64F)

I cannot find the likely command under Imgproc.

Can I measure blurr with this package?

**Comment by yeatse** [comment]
According to the [documentation](https://docs.opencv.org/3.4/d4/d86/group__imgproc__filter.html#gad78703e4c8fe703d479c1860d76429e6), you need to include `<opencv2/imgproc.hpp>` in order to use the laplacian function. In Swift, you can call `Imgproc.Laplacian` instead. For example: `Imgproc.Laplacian(src: gray, dst: result, ddepth: CvType.CV_64F)`.

**Comment by junmcenroe** [comment]
Dear yeatse

Thanks for your advice.
I tried following code (Sorry cannot copy&Past with correct indent)

let src = Mat(uiImage: UIImage(named: "cat0")!)
// Transform source image to gray if it is not already
let gray: Mat
if (src.channels() == 3) {
    gray = Mat()
    Imgproc.cvtColor(src: src, dst: gray, code: .COLOR_BGR2GRAY)
} else {
    gray = src
}
let out = Mat()
let laplacian: Void = Imgproc.Laplacian(src: gray, dst: out, ddepth: CvType.CV_64F)
print("Laplacian value2: \(laplacian)")

But print result (). Because Xcode forced me set Void to use Imgproc.Laplacian call 

What wrong?
I just installed your spm with your procedure, not additional header such as <opencv2/imgproc.hpp> 

Any advice?

**Comment by yeatse** [comment]
In C++, this function does not return a value. Instead, the result is stored in the `out` parameter. For further details, please refer the documentation:
<img width="521" alt="image" src="https://github.com/yeatse/opencv-spm/assets/6036532/9ee43078-ac73-48d6-872b-e563f0834269">

**Comment by junmcenroe** [comment]
Dear yeatse

When I use OpenCV on Python, I can get the value with
**
import cv2

laplacian = cv2.Laplacian(gray, cv2.CV_64F) 
print("laplacian.var() value？",laplacian.var())
if laplacian.var() < 100:
   text = "Blurry"
else:
   text = "Not Blurry"
**
But Dit C++, Swift not support this?

**Comment by yeatse** [comment]
You can ask ChatGPT or New Bing
<img width="1007" alt="image" src="https://github.com/yeatse/opencv-spm/assets/6036532/499d88f1-960a-4e7c-b012-bad34a7c77f1">
The equivalent of `meanStdDev` in Swift is `Core.meanStdDev`.
